### ISSUE TITLE
Deprecated meta tag "apple-mobile-web-app-capable"

### ISSUE THREAD

**Issue by Patta** [benjaminkott/bootstrap_package#1532]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v11.5 LTS
* [x] Can you reproduce the problem on TYPO3 v12.4 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

Browser console log message:
`<meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">`

## Versions

TYPO3 12.4.22
bootstrap_package 15.0.0
